# Generated by Django 2.1.2 on 2018-12-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labbook',
            name='document_code',
        ),
        migrations.RemoveField(
            model_name='relatedfile',
            name='document_code',
        ),
        migrations.RemoveField(
            model_name='report',
            name='document_code',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='document_code',
        ),
    ]
