# Generated by Django 2.1.2 on 2018-12-24 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20181224_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labbook',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Document author(s)'),
        ),
        migrations.AlterField(
            model_name='labbook',
            name='project',
            field=models.ManyToManyField(to='coreapp.Project', verbose_name='Associated project(s)'),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Document author(s)'),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='project',
            field=models.ManyToManyField(to='coreapp.Project', verbose_name='Associated project(s)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Document author(s)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ManyToManyField(to='coreapp.Project', verbose_name='Associated project(s)'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Document author(s)'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='project',
            field=models.ManyToManyField(to='coreapp.Project', verbose_name='Associated project(s)'),
        ),
    ]
