# Generated by Django 2.1.4 on 2019-01-23 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20181224_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labbook',
            name='author',
        ),
        migrations.AddField(
            model_name='labbook',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Main author'),
        ),
        migrations.RemoveField(
            model_name='labbook',
            name='project',
        ),
        migrations.AddField(
            model_name='labbook',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.Project', verbose_name='Associated project'),
        ),
        migrations.RemoveField(
            model_name='relatedfile',
            name='author',
        ),
        migrations.AddField(
            model_name='relatedfile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Main author'),
        ),
        migrations.RemoveField(
            model_name='relatedfile',
            name='project',
        ),
        migrations.AddField(
            model_name='relatedfile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.Project', verbose_name='Associated project'),
        ),
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Main author'),
        ),
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.Project', verbose_name='Associated project'),
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='author',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Main author'),
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='project',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.Project', verbose_name='Associated project'),
        ),
    ]
