# Generated by Django 2.1.4 on 2019-01-23 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_auto_20190123_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='study_plan',
        ),
        migrations.AddField(
            model_name='report',
            name='study_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.StudyPlan', verbose_name='Study plan'),
        ),
    ]
