# Generated by Django 2.1.4 on 2019-01-30 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_auto_20190123_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labbook',
            name='content_descr',
        ),
        migrations.RemoveField(
            model_name='relatedfile',
            name='content_descr',
        ),
        migrations.AddField(
            model_name='labbook',
            name='title',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Document title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatedfile',
            name='title',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Document title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.TextField(verbose_name='Document title'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='title',
            field=models.TextField(verbose_name='Document title'),
        ),
    ]
