# Generated by Django 2.1.4 on 2019-02-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_auto_20190130_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.Project', verbose_name='Associated project(s)'),
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='project',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.Project', verbose_name='Associated project(s)'),
        ),
    ]
