# Generated by Django 2.1.4 on 2019-02-10 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_auto_20190210_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedfile',
            name='author',
        ),
        migrations.AddField(
            model_name='relatedfile',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.Project', verbose_name='Associated project'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.Project', verbose_name='Associated project'),
        ),
    ]
